name = "tooth-harmony-pro-api"
main = "src/index.ts"
compatibility_date = "2026-03-21"
workers_dev = true




[[d1_databases]]
binding = "DB"
database_name = "tooth-harmony-pro-db"
database_id = "949efb7f-902f-4249-abb0-4b2c7dcbc59e"
migrations_dir = "migrations"


